apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-server
  template:
    metadata:
      labels:
        app: front-server
    spec:
      containers:
        - name: front-server-container
          image: nginx:latest
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: html-config
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: html-config
          configMap:
            name: html-config
